### ISSUE TITLE
DLPF mode and the accelerometer

### ISSUE THREAD

**Issue by DamarXCV** [wollewald/ICM20948_WE#2]
Hi,

in `examples\ICM20948_08_cycle\ICM20948_08_cycle.ino` you wrote that you get wrong data if DLPF is applied. That is mostly intended because you NEED to set the acc DLPF to 7, if you want to use the DLPF, every other setting is out of specs. Take a look at  [ACCEL_DLPFCFG, Tabel 19, Page 65](https://invensense.tdk.com/wp-content/uploads/2016/06/DS-000189-ICM-20948-v1.3.pdf).
And the sample rate divider is intended to work with a "disabled" DLPF (aka 1X AVG) as you can see in the tabel and also not strange. :D

**Comment by wollewald** [comment]
@DamarXCV , great thanks for the explanation. And evene more thanks for updating alle the example sketches. This is very helpful!
